/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Prestamo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Prestamo.class.getName());

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCredito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfInteresMax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfInteresMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPeriodoMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPeriodoMin = new javax.swing.JTextField();
        jcbIncremento = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnCalculoPagos = new javax.swing.JButton();
        jbtnAmort = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Crédito:");

        jLabel2.setText("Máximo:");

        jLabel3.setText("Mínimo:");

        jLabel4.setText("% Máximo:");

        jtfPeriodoMax.addActionListener(this::jtfPeriodoMaxActionPerformed);

        jLabel5.setText("% Mínimo");

        jcbIncremento.setText("Incremento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.10", "0.25", "0.50", "1.00" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Periodo", "Interes %", "Pago", "Total Pagado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtnCalculoPagos.setText("Pago");
        jbtnCalculoPagos.addActionListener(this::jbtnCalculoPagosActionPerformed);

        jbtnAmort.setText("Amortización");
        jbtnAmort.addActionListener(this::jbtnAmortActionPerformed);

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Instrucciones");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prestamo en...");

        jMenuItem3.setText("Años");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Meses");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbIncremento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfCredito)
                        .addComponent(jtfInteresMax, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jtfInteresMin)
                        .addComponent(jtfPeriodoMax)
                        .addComponent(jtfPeriodoMin)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbtnCalculoPagos)
                        .addGap(41, 41, 41)
                        .addComponent(jbtnAmort)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnCalculoPagos)
                            .addComponent(jbtnAmort))
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbIncremento)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPeriodoMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPeriodoMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPeriodoMaxActionPerformed

    private void jbtnCalculoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalculoPagosActionPerformed
        double credito = Double.parseDouble(jtfCredito.getText());
int periodoMin = Integer.parseInt(jtfPeriodoMin.getText());
int periodoMax = Integer.parseInt(jtfPeriodoMax.getText());

double interesMin = Double.parseDouble(jtfInteresMin.getText());
double interesMax = Double.parseDouble(jtfInteresMax.getText());

double incremento = Double.parseDouble(
        jComboBox1.getSelectedItem().toString()
);

javax.swing.table.DefaultTableModel modelo =
        new javax.swing.table.DefaultTableModel();

modelo.addColumn("Periodo");
modelo.addColumn("Interés %");
modelo.addColumn("Pago");
modelo.addColumn("Total Pagado");

for (int periodo = periodoMin; periodo <= periodoMax; periodo++) {

    for (double interes = interesMin;
            interes <= interesMax + 0.000001;
            interes += incremento) {

        double tasaMensual = (interes / 100.0) / 12.0;

        double pago;

        if (tasaMensual == 0) {
            pago = credito / periodo;
        } else {
            pago = credito *
                    (tasaMensual * Math.pow(1 + tasaMensual, periodo))
                    / (Math.pow(1 + tasaMensual, periodo) - 1);
        }

        double totalPagado = pago * periodo;

        modelo.addRow(new Object[]{
            periodo,
            String.format("%.2f", interes),
            String.format("%.2f", pago),
            String.format("%.2f", totalPagado)
        });
    }
}

jTable1.setModel(modelo);          
    }//GEN-LAST:event_jbtnCalculoPagosActionPerformed

    private void jbtnAmortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAmortActionPerformed
        int fila = jTable1.getSelectedRow();

if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un préstamo de la tabla primero.");
    return;
}

double credito = Double.parseDouble(jtfCredito.getText());
int periodo = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
double interes = Double.parseDouble(jTable1.getValueAt(fila, 1).toString());
double pago = Double.parseDouble(jTable1.getValueAt(fila, 2).toString());

double tasaMensual = (interes / 100.0) / 12.0;

javax.swing.table.DefaultTableModel modelo =
        new javax.swing.table.DefaultTableModel();

modelo.addColumn("Periodo");
modelo.addColumn("Pago");
modelo.addColumn("Interés");
modelo.addColumn("Capital");
modelo.addColumn("Saldo Pendiente");
modelo.addColumn("Interés Acumulado");

double saldo = credito;
double interesAcumulado = 0;

for (int i = 1; i <= periodo; i++) {

    double interesPeriodo = saldo * tasaMensual;
    double capital = pago - interesPeriodo;

    if (i == periodo) {
        capital = saldo;
        pago = capital + interesPeriodo;
    }

    saldo -= capital;
    interesAcumulado += interesPeriodo;

    if (saldo < 0.01) {
        saldo = 0;
    }

    modelo.addRow(new Object[]{
        i,
        String.format("%.2f", pago),
        String.format("%.2f", interesPeriodo),
        String.format("%.2f", capital),
        String.format("%.2f", saldo),
        String.format("%.2f", interesAcumulado)
    });
}

javax.swing.JTable tablaAmortizacion =
        new javax.swing.JTable(modelo);

javax.swing.JScrollPane scroll =
        new javax.swing.JScrollPane(tablaAmortizacion);

javax.swing.JOptionPane.showMessageDialog(
        this,
        scroll,
        "Tabla de Amortización",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jbtnAmortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Prestamo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAmort;
    private javax.swing.JButton jbtnCalculoPagos;
    private javax.swing.JLabel jcbIncremento;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfInteresMax;
    private javax.swing.JTextField jtfInteresMin;
    private javax.swing.JTextField jtfPeriodoMax;
    private javax.swing.JTextField jtfPeriodoMin;
    // End of variables declaration//GEN-END:variables
}
